new upload function

diff --git a/bashrc_solaris b/bashrc_solaris
--- a/bashrc_solaris
+++ b/bashrc_solaris
@@ -5,16 +5,43 @@ export PATH="/usr/local/gnu/bin:$PATH"
 alias ls="/usr/local/gnu/bin/ls -h --color=always"
 
 function upload () {
-	if [ "$2" == "" ]
+	if [ -z "$1" ]
 	then
-		repo=testing
-	else
-		repo=$2
+		echo "Usage rpmsubmit packagename [repo]"
+		return 2
 	fi
-	pushd ~/rpmbuild
-	find . -name $1*.rpm | xargs rpm --resign
-	scp $(find . -name $1*.rpm) rpm:/rpm/CHECK_PEND.$repo
-	popd
+
+	pushd ~/rpmbuild &> /dev/null
+	vnum=`ls -lt SRPMS/$1-* | awk 'NR == 1 { print $NF }' | cut -d/ -f2- | egrep -o "[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*-[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*.src.rpm$" | sed "s/.src.rpm//g"`
+	if [ vnum == "" ]
+	then
+		echo "File not found."
+		return 1
+	fi
+	echo "Most recent appears to be $vnum"
+
+	#check for other breakout packages
+
+	OTHER=`grep "%package -n" SPECS/$1.spec | grep -v "#%package" | cut -d' ' -f3`
+	PKGS=""
+	
+	for i in $OTHER
+	do
+		PKGS="$PKGS RPMS/sparc64/$i-$vnum*rpm "
+	done
+
+	echo $PKGS
+	
+	exit 0
+
+	repo="testing"
+	if ! [ -z "$2" ]
+	then
+		repo="$2"
+	fi
+
+	rpm --resign SRPMS/$1-$vnum.src.rpm RPMS/sparc64/$1*$vnum* && scp SRPMS/$1-$vnum.src.rpm RPMS/sparc64/$1*$vnum* rpm:/rpm/CHECK_PEND.$repo
+	popd &> /dev/null
 }
 
 function cleanpath() {
